name: 17wanxiaoCheckin

on:
  push:
   branches: [ master ]
  pull_request:
   branches: [ master ]
  schedule:
   - cron: 0 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pip
      run: pip3 install requests pycryptodome

    - name: HealthyCheckIn
      run: python3 index.py
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        SCKEY: ${{secrets.SCKEY}}
        SEND_EMAIL: ${{secrets.SEND_EMAIL}}
        SEND_PWD: ${{secrets.SEND_PWD}}
        RECEIVE_EMAIL: ${{secrets.RECEIVE_EMAIL}}
